name = "Go Couchbase"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"
destination = "build/golang_s.wasm"

[[registry.pull.sources]]
target = "wasmcloud:couchbase"
source = "file://../../wit"
