name = "Rust Couchbase"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "wasmcloud:couchbase"
source = "file://../../wit"
