services:
  couchbase:
    image: couchbase:latest
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11207:11207
      - 11211:11211
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=test
      - COUCHBASE_CONNECTION_STRING=localhost
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchbase-init:
    image: couchbase:latest
    depends_on:
      - couchbase
    volumes:
      - ./init-couchbase.sh:/init-couchbase.sh
    entrypoint: '/init-couchbase.sh'
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.58
    restart: always
    ports:
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
      - '4317:4317'
      - '4318:4318'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      COLLECTOR_OTLP_ENABLED: 'true'
volumes:
  couchbase-data:
