apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: couchbase
  annotations:
    version: v0.2.0
    description: 'Couchbase capability provider demonstration with wasmCloud'
spec:
  policies:
    - name: nats-kv
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: nats-kv
  components:
    - name: component
      type: component
      properties:
        image: file://./components/rust/build/rust_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 100
        # Link the component to the provider on wasmcloud:couchbase/document
        - type: link
          properties:
            namespace: wasmcloud
            package: couchbase
            interfaces: [document]
            target:
              name: couchbase
              secrets:
                - name: password
                  properties:
                    policy: nats-kv
                    key: couchbase_password
              config:
                - name: provider-config
                  properties:
                    username: 'Administrator'
                    bucketName: 'test'
                    connectionString: 'localhost'

    - name: couchbase
      type: capability
      properties:
        image: file://./build/wasmcloud-provider-couchbase.par.gz
        id: couchbase
    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 127.0.0.1:8080
