package wasmcloud:provider-keyvalue-couchbase;

world interfaces {
    export wasmcloud:couchbase/document@0.1.0-draft;
    // export wasmcloud:couchbase/fts@0.1.0-draft;
    // export wasmcloud:couchbase/subdocument-lookup@0.1.0-draft;
    // export wasmcloud:couchbase/subdocument-mutate@0.1.0-draft;
    // export wasmcloud:couchbase/sqlpp@0.1.0-draft;
}
