package wasmcloud:couchbase@0.1.0-draft;

world interfaces {
    export document;
    // export fts@0.1.0-draft;
    // export subdocument-lookup@0.1.0-draft;
    // export subdocument-mutate@0.1.0-draft;
    // export sqlpp@0.1.0-draft;
}
