package wasmcloud:couchbase@0.1.0-draft;

/// Mappings of SQL++ (formerly known as N1QL) to WebAssembly (WIT) types
///
interface sqlpp-types {
  /// Errors that can occur when a SQL++ query is performed
  variant sqlpp-query-error {
    /// A completely unexpected query error
    unexpected(string),
  }

  /// An embedding of SQL++ values to WebAssembly types
  ///
  /// This type should be used in building queries, and also in parsing/processing results,
  /// as it is used for both parameters and returned results from queries.
  variant sqlpp-value {
    /// A NULL value
    null,
  }
}