// Generated by `wit-bindgen-wrpc-go` 0.1.0. DO NOT EDIT!
// interfaces package contains wRPC bindings for `interfaces` world
package interfaces

import (
	exports__wrpc__keyvalue__atomics "github.com/couchbase-examples/wasmcloud-provider-couchbase/bindings/exports/wrpc/keyvalue/atomics"
	exports__wrpc__keyvalue__store "github.com/couchbase-examples/wasmcloud-provider-couchbase/bindings/exports/wrpc/keyvalue/store"
	wrpc "github.com/wrpc/wrpc/go"
)

func Serve(c wrpc.Client, h interface {
	exports__wrpc__keyvalue__store.Handler
	exports__wrpc__keyvalue__atomics.Handler
}) (stop func() error, err error) {
	stops := make([]func() error, 0, 2)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__wrpc__keyvalue__store.ServeInterface(c, h)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop1, err := exports__wrpc__keyvalue__atomics.ServeInterface(c, h)
	if err != nil {
		return
	}
	stops = append(stops, stop1)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		if err := stop1(); err != nil {
			return err
		}
		return nil
	}
	return
}
