// Generated by `wit-bindgen-wrpc-go` 0.10.0. DO NOT EDIT!
// interfaces package contains wRPC bindings for `interfaces` world
package interfaces

import (
	exports__wasmcloud__couchbase__document "github.com/couchbase-examples/wasmcloud-provider-couchbase/bindings/exports/wasmcloud/couchbase/document"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__wasmcloud__couchbase__document.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__wasmcloud__couchbase__document.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
